[WinEventLog://Microsoft-Windows-Windows Defender/Operational]
disabled = 0
index = default
current_only = 0
start_from = oldest
checkpointInterval = 5

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = default
current_only = 0
start_from = oldest
checkpointInterval = 5


[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = default
current_only = 0
start_from = oldest
checkpointInterval = 5

[WinEventLog://Microsoft-Windows-Windows Firewall With Advanced Security/Firewall]
disabled = 0
index = default
current_only = 0
start_from = oldest
checkpointInterval = 5




